import { Inter } from "next/font/google";

import "../app/reset.scss";

import Providers from "../components/Providers";
import Appbar from "../components/Appbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PortfolioManager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body className={inter.className}>
      <Providers>
          <Appbar />
          {children}
      </Providers>
      </body>
    </html>
  );
}
